---
:ems:
  :ems_hawkular:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
    :jdr:
      :generation_timeout: 3.minutes
:ems_refresh:
  :hawkular:
    :refresh_interval: 15.minutes
:http_proxy:
  :hawkular:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_datawarehouse: info
:product:
  :datawarehouse_manager: false
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_hawkular:
        :poll: 10.seconds
      :event_catcher_hawkular_datawarehouse:
        :alertable_tenants: ['_system', '_ops']
        :poll: 1.minute
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_hawkular: {}
